version: '3.8'

services:
  web:
    depends_on:
      - api
    build: ./app
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:4000
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app/package-lock.json
          action: rebuild
        - path: ./app
          target: /app
          action: sync

  api:
    depends_on:
      - db
    build: ./api
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://db/images
      - PORT=4000
      - DOMAIN=http://localhost:4000
    develop:
      watch:
        - path: ./api/package.json
          action: rebuild
        - path: ./api/package-lock.json
          action: rebuild
        - path: ./api
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - images:/data/db

volumes:
  images:
